# Generated by Django 5.2.4 on 2025-08-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Proyecto')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría (ej: Web, Diseño, Mobile)')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Descripción Corta')),
                ('problem_statement', models.TextField(verbose_name='Planteamiento del Problema')),
                ('solution_details', models.TextField(verbose_name='Detalles de la Solución')),
                ('process_steps', models.TextField(blank=True, null=True, verbose_name='Pasos del Proceso (ej: Markdown/HTML)')),
                ('technologies_used', models.CharField(max_length=500, verbose_name='Tecnologías Utilizadas (ej: React, Django, SQL)')),
                ('challenges_faced', models.TextField(blank=True, null=True, verbose_name='Desafíos Enfrentados')),
                ('results_impact', models.TextField(verbose_name='Resultados e Impacto')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Imagen Principal del Proyecto')),
                ('deployment_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de Despliegue/Demo')),
                ('github_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace a GitHub')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['title'],
            },
        ),
    ]
